/**
 * The spread templates, as data — ported from liketrek/trek's
 * client/src/components/Studio/bookTemplates.data.ts (same AGPLv3 license).
 *
 * ── Where these come from ────────────────────────────────────────────────
 *
 * Not written by hand, and not generated. Upstream built them in their own
 * Studio editor and read the finished spread back out of the document —
 * design is a matter of taste, and taste is not something a layout function
 * arrives at by reasoning. A page somebody actually composed — a panel bled
 * off one edge, a photo strip at two sizes with the labels set under them —
 * beats a page a function reasoned its way to, every time. See
 * autoLayout.ts's own header comment for why this fork otherwise leans on
 * 12 programmatic templates instead of hand-drawing a set of its own.
 *
 * ── Adapted, not copied verbatim ─────────────────────────────────────────
 *
 * Every element here keeps its geometry and its drawn content unchanged.
 * Three adjustments were made turning upstream's raw export into this file:
 *
 * 1. Fields this fork's schema doesn't carry are dropped: `textScale`,
 *    `weight` and `stale` off the travel-element mixin, and `autoColor`,
 *    `autoIconColor`, `iconColor`, `showIcon`, `showLabel` off badges —
 *    server-side zod would silently strip them on save anyway (no
 *    `.strict()` on these objects), but keeping them here would claim they
 *    do something in a fork whose renderer never reads them.
 * 2. `list` elements (a pros/cons panel folded into a photo spread) were
 *    removed outright, not just emptied. Upstream's own `applyTemplate`
 *    never fills a `list` element — its `TemplateEntry` has no pros/cons
 *    field to fill it from — so a template applied there always showed
 *    literal leftover debug text ("TEST1"/"TEST1") from whoever drew it.
 *    This fork has real pros/cons data and fills it itself, as a compact
 *    footer on the entry's own page — see autoLayout.ts's `entrySpread`
 *    and `prosConsFooterElements` — so a second, always-empty list panel
 *    baked into the template would just be dead space next to a live one.
 * 3. Two of upstream's six spreads (`ref-2`, `ref-3`) carry a full-bleed
 *    "hero" photo that runs from one page straight across the gutter into
 *    the other. That is a legitimate choice on a spread meant to be viewed
 *    uncut — but this fork's auto layout exports single leaves for a real
 *    print vendor's uploader ("Páginas sueltas"), where a straddling photo
 *    comes out as two unrelated fragments on two separate sheets. Rather
 *    than trim the drawing, `referenceTemplates.ts`'s own picker filters
 *    them out of automatic selection the same way `crossesGutter` already
 *    filters the 12 programmatic templates in autoLayout.ts — both spreads
 *    are kept here, complete and unedited, simply never auto-picked.
 * 4. Any template carrying a travel element — map, stats, countries,
 *    badge, icon or list — is excluded from automatic picking too
 *    (`hasTravelElement` in referenceTemplates.ts), for a content reason
 *    rather than a geometric one: everywhere else in this fork, a travel
 *    element is something a person chose from Studio's own "Travel" panel,
 *    never something auto-layout decides to add on its own. `ref-1`'s
 *    `stats`/`countries` panel is what surfaced this — the journey's own
 *    totals, the same on every page, not anything about whichever entry
 *    the page got attached to, and scored purely by its one photo frame it
 *    kept winning nearly every one-photo, no-story entry (a common shape),
 *    so the same SUMMARY/COUNTRIES panel kept repeating across the book —
 *    but the rule covers every kind, not just ref-1's own, which is also
 *    why `ref-5`'s two coords badges keep it out of automatic picking.
 *    Every one of the six is kept here complete and unedited; three of
 *    them (`ref-1`, `ref-2`, `ref-3`) are simply never auto-picked because
 *    of this, and a fourth (`ref-5`) because of it too.
 *
 * ── Why the numbers are fractions ────────────────────────────────────────
 *
 * Every frame is divided by the page it was drawn on — x and w by one
 * page's width, y and h by its height — so a template built on a 210mm
 * square lays out on any other page size without being redrawn. The gutter
 * sits at x = 1.0 in this space (one page width in), which is what the
 * crossing check above tests against directly, with no page size needed.
 *
 * ── What gets filled in ──────────────────────────────────────────────────
 *
 * Elements carrying a `binding` take their text from the entry (see
 * referenceTemplates.ts's `applyReferenceTemplate`); empty photo frames
 * take its photographs in order; a `coords` or `distance` badge takes what
 * the entry/journey can answer. Everything else — the panels, the country
 * codes, the "weather"/"mood" badges, the stats this fork has no data
 * for — is the design as upstream drew it, and is kept as drawn: a badge
 * or figure the entry cannot answer keeps the words it was drawn with,
 * rather than showing a blank or a zero.
 */
import type { BookElement } from '../../types/book'

export interface SpreadTemplate {
  id: string
  background: string | null
  /** Frames and sizes are fractions of one page — see the header comment above. */
  elements: BookElement[]
}

export const SPREAD_TEMPLATES: SpreadTemplate[] = [
  {
    id: 'ref-1',
    background: null,
    elements: [
      {
        id: 'p-iy13loy',
        frame: {
          x: 0.0238,
          y: 0.0238,
          w: 0.9524,
          h: 0.9524,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        kind: 'photo',
        photoId: null,
        fit: 'cover',
        focalX: 0.572289143475242,
        focalY: 0.5726791042512355,
        radius: 0.0238,
        filter: 'none',
        mask: null,
        frameStyle: 'none',
      } as BookElement,
      {
        id: 's-kafy6t4',
        frame: {
          x: 1.5898,
          y: 0.0238,
          w: 0.3864,
          h: 0.9524,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        kind: 'shape',
        shape: 'rect',
        fill: '#111111',
        gradient: 'none',
        stroke: null,
        strokeWidth: 0,
        strokeStyle: 'solid',
        radius: 0,
      } as BookElement,
      {
        id: 't-v4jhfu6',
        frame: {
          x: 1.5898,
          y: 0.0563,
          w: 0.3864,
          h: 0.0613,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        kind: 'text',
        text: 'COUNTRIES',
        font: 'sans',
        size: 0.1429,
        weight: 700,
        italic: false,
        align: 'center',
        leading: 1.1,
        tracking: -0.02,
        color: '#ffffff',
        binding: null,
        overridden: true,
      } as BookElement,
      {
        id: 't-nh804rp',
        frame: {
          x: 1.1136,
          y: 0.0563,
          w: 0.3864,
          h: 0.0613,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        kind: 'text',
        text: 'SUMMARY',
        font: 'sans',
        size: 0.1429,
        weight: 700,
        italic: false,
        align: 'center',
        leading: 1.1,
        tracking: -0.02,
        color: '#111111',
        binding: null,
        overridden: true,
      } as BookElement,
      {
        id: 's-8c3kwzk',
        frame: {
          x: 1.0812,
          y: 0.1757,
          w: 0.4511,
          h: 0.5743,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        font: 'sans',
        color: '#1a1a1a',
        accent: '#111111',
        kind: 'stats',
        metrics: ['distance', 'days', 'steps', 'photos', 'countries', 'places'],
        layout: 'grid',
        showIcons: true,
        units: 'metric',
        values: {
          distance: 352677,
          days: 1,
          steps: 2,
          photos: 3,
          countries: 2,
          places: 0,
          furthest: 352677,
        },
      } as BookElement,
      {
        id: 'b-15vswaz',
        frame: {
          x: 1.1768,
          y: 0.7685,
          w: 0.2587,
          h: 0.066,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        font: 'sans',
        color: '#1a1a1a',
        accent: '#111111',
        kind: 'badge',
        variant: 'distance',
        text: '0 km',
        sub: 'Distance',
        code: null,
        style: 'chip',
      } as BookElement,
      {
        id: 'c-jdsxmvn',
        frame: {
          x: 1.628,
          y: 0.2315,
          w: 0.31,
          h: 0.537,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        font: 'sans',
        color: '#ffffff',
        accent: '#ffffff',
        kind: 'countries',
        codes: ['DE', 'NL'],
        names: ['Germany', 'Netherlands'],
        layout: 'list',
        showFlag: false,
        showName: true,
        align: 'center',
      } as BookElement,
    ],
  },
  {
    id: 'ref-2',
    background: null,
    elements: [
      {
        id: 's-f7yltlr',
        frame: {
          x: -0.1264,
          y: 0.6775,
          w: 0.5595,
          h: 0.5973,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        kind: 'shape',
        shape: 'flower-5',
        fill: '#111111',
        gradient: 'none',
        stroke: null,
        strokeWidth: 0,
        strokeStyle: 'solid',
        radius: 0,
      } as BookElement,
      {
        id: 's-0fpxqfa',
        frame: {
          x: 1.0762,
          y: 0.6437,
          w: 0.8635,
          h: 0.2829,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        kind: 'shape',
        shape: 'rect',
        fill: '#111111',
        gradient: 'none',
        stroke: '#11224f',
        strokeWidth: 0.0024,
        strokeStyle: 'solid',
        radius: 0,
      } as BookElement,
      {
        id: 'p-b5dnke1',
        frame: {
          x: 0.0238,
          y: 0.0238,
          w: 1.9524,
          h: 0.3062,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        kind: 'photo',
        photoId: 69,
        fit: 'cover',
        focalX: 0.42168673729754674,
        focalY: 0.23833399057977409,
        radius: 0,
        filter: 'none',
        mask: null,
        frameStyle: 'none',
      } as BookElement,
      {
        id: 't-kvtn36a',
        frame: {
          x: 0.0762,
          y: 0.3843,
          w: 0.8476,
          h: 0.0479,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        kind: 'text',
        text: 'Lorem ipsum dolor sit amet',
        font: 'sans',
        size: 0.1048,
        weight: 700,
        italic: false,
        align: 'left',
        leading: 1.1,
        tracking: -0.02,
        color: '#1a1a1a',
        binding: {
          source: 'entry.title',
          entryId: 62,
        },
        overridden: false,
      } as BookElement,
      {
        id: 't-cnhlrmk',
        frame: {
          x: 0.0762,
          y: 0.452,
          w: 0.8476,
          h: 0.1917,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        kind: 'text',
        text: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.',
        font: 'sans',
        size: 0.0476,
        weight: 400,
        italic: false,
        align: 'left',
        leading: 1.55,
        tracking: 0,
        color: '#1a1a1a',
        binding: {
          source: 'entry.story',
          entryId: 62,
        },
        overridden: false,
      } as BookElement,
      {
        id: 't-gabkf9x',
        frame: {
          x: 1.0762,
          y: 0.3843,
          w: 0.8476,
          h: 0.1917,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        kind: 'text',
        text: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.',
        font: 'sans',
        size: 0.0476,
        weight: 400,
        italic: false,
        align: 'left',
        leading: 1.55,
        tracking: 0,
        color: '#1a1a1a',
        binding: {
          source: 'entry.story',
          entryId: 62,
        },
        overridden: false,
      } as BookElement,
      {
        id: 's-vkl7noe',
        frame: {
          x: 1.0762,
          y: 0.6034,
          w: 0.5,
          h: 0.0024,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        kind: 'shape',
        shape: 'rect',
        fill: '#141414',
        gradient: 'none',
        stroke: null,
        strokeWidth: 0,
        strokeStyle: 'solid',
        radius: 0,
      } as BookElement,
      {
        id: 'p-s3anbzj',
        frame: {
          x: 0.1836,
          y: 0.7134,
          w: 0.2,
          h: 0.2171,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        kind: 'photo',
        photoId: 68,
        fit: 'cover',
        focalX: 0.5,
        focalY: 0.5,
        radius: 0,
        filter: 'none',
        mask: null,
        frameStyle: 'polaroid',
      } as BookElement,
      {
        id: 'p-874qk6j',
        frame: {
          x: 0.5893,
          y: 0.7134,
          w: 0.2,
          h: 0.2171,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        kind: 'photo',
        photoId: 69,
        fit: 'cover',
        focalX: 0.5,
        focalY: 0.5,
        radius: 0,
        filter: 'none',
        mask: 'heart',
        frameStyle: 'polaroid',
      } as BookElement,
      {
        id: 'b-gmtenyt',
        frame: {
          x: 0.5993,
          y: 0.8893,
          w: 0.18,
          h: 0.05,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        font: 'sans',
        color: '#1a1a1a',
        accent: '#111111',
        kind: 'badge',
        variant: 'coords',
        text: "51\u00b010'N 10\u00b027'E",
        sub: '',
        code: null,
        style: 'plain',
      } as BookElement,
      {
        id: 'b-4rd95kg',
        frame: {
          x: 0.1936,
          y: 0.8893,
          w: 0.18,
          h: 0.05,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        font: 'sans',
        color: '#1a1a1a',
        accent: '#111111',
        kind: 'badge',
        variant: 'coords',
        text: "51\u00b010'N 10\u00b027'E",
        sub: '',
        code: null,
        style: 'plain',
      } as BookElement,
    ],
  },
  {
    id: 'ref-3',
    background: null,
    elements: [
      {
        id: 'p-sa5cabi',
        frame: {
          x: 0.025,
          y: 0.025,
          w: 1.9512,
          h: 0.5919,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        kind: 'photo',
        photoId: null,
        fit: 'cover',
        focalX: 0.5,
        focalY: 0.5,
        radius: 0,
        filter: 'none',
        mask: null,
        frameStyle: 'none',
      } as BookElement,
      {
        id: 't-kws7inb',
        frame: {
          x: 0.054,
          y: 0.688,
          w: 0.8919,
          h: 0.2294,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        kind: 'text',
        text: 'Lorem ipsum dolor sit amet',
        font: 'sans',
        size: 0.2381,
        weight: 700,
        italic: false,
        align: 'left',
        leading: 1.1,
        tracking: -0.02,
        color: '#1a1a1a',
        binding: {
          source: 'entry.title',
          entryId: 62,
        },
        overridden: false,
      } as BookElement,
      {
        id: 't-1zzydde',
        frame: {
          x: 1.0808,
          y: 0.6542,
          w: 0.8385,
          h: 0.1917,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        kind: 'text',
        text: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.',
        font: 'sans',
        size: 0.0476,
        weight: 400,
        italic: false,
        align: 'left',
        leading: 1.55,
        tracking: 0,
        color: '#1a1a1a',
        binding: {
          source: 'entry.story',
          entryId: 62,
        },
        overridden: false,
      } as BookElement,
      {
        id: 't-kht4sfu',
        frame: {
          x: 0.054,
          y: 0.6542,
          w: 0.36,
          h: 0.0314,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        kind: 'text',
        text: 'August 19, 2026',
        font: 'sans',
        size: 0.0762,
        weight: 700,
        italic: false,
        align: 'left',
        leading: 1.1,
        tracking: -0.02,
        color: '#1a1a1a',
        binding: {
          source: 'entry.date',
          entryId: 62,
          value: '2026-08-19',
        },
        overridden: false,
      } as BookElement,
    ],
  },
  {
    id: 'ref-4',
    background: null,
    elements: [
      {
        id: 's-19c5q0x',
        frame: {
          x: -0.1119,
          y: 0.4164,
          w: 0.7143,
          h: 0.7143,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        kind: 'shape',
        shape: 'ellipse',
        fill: '#141414',
        gradient: 'none',
        stroke: null,
        strokeWidth: 0,
        strokeStyle: 'solid',
        radius: 0,
      } as BookElement,
      {
        id: 'p-e8ee9j8',
        frame: {
          x: 0.0816,
          y: 0.0763,
          w: 0.3367,
          h: 0.3827,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        kind: 'photo',
        photoId: null,
        fit: 'cover',
        focalX: 0.5,
        focalY: 0.5,
        radius: 0,
        filter: 'none',
        mask: null,
        frameStyle: 'polaroid',
      } as BookElement,
      {
        id: 'p-fimcc5x',
        frame: {
          x: 0.5662,
          y: 0.202,
          w: 0.3367,
          h: 0.3827,
        },
        rotation: -10.1,
        opacity: 1,
        locked: false,
        kind: 'photo',
        photoId: null,
        fit: 'cover',
        focalX: 0.5,
        focalY: 0.5,
        radius: 0,
        filter: 'none',
        mask: null,
        frameStyle: 'polaroid',
      } as BookElement,
      {
        id: 'p-nva57q1',
        frame: {
          x: 0.1739,
          y: 0.5,
          w: 0.3367,
          h: 0.3827,
        },
        rotation: 5.1,
        opacity: 1,
        locked: false,
        kind: 'photo',
        photoId: null,
        fit: 'cover',
        focalX: 0.5,
        focalY: 0.5,
        radius: 0,
        filter: 'none',
        mask: 'seal',
        frameStyle: 'polaroid',
      } as BookElement,
      {
        id: 't-7zfrwms',
        frame: {
          x: 1.0762,
          y: 0.1605,
          w: 0.8476,
          h: 0.0895,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        kind: 'text',
        text: 'Lorem ipsum dolor sit amet',
        font: 'sans',
        size: 0.1429,
        weight: 700,
        italic: false,
        align: 'left',
        leading: 1.1,
        tracking: -0.02,
        color: '#1a1a1a',
        binding: {
          source: 'entry.title',
          entryId: 63,
        },
        overridden: false,
      } as BookElement,
      {
        id: 't-culm58m',
        frame: {
          x: 1.0762,
          y: 0.2676,
          w: 0.8476,
          h: 0.2073,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        kind: 'text',
        text: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.',
        font: 'sans',
        size: 0.0476,
        weight: 400,
        italic: false,
        align: 'left',
        leading: 1.55,
        tracking: 0,
        color: '#1a1a1a',
        binding: {
          source: 'entry.story',
          entryId: 62,
        },
        overridden: false,
      } as BookElement,
      {
        id: 't-x3ysuxa',
        frame: {
          x: 1.0762,
          y: 0.116,
          w: 0.36,
          h: 0.0314,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        kind: 'text',
        text: 'August 19, 2026',
        font: 'sans',
        size: 0.069,
        weight: 700,
        italic: false,
        align: 'left',
        leading: 1.1,
        tracking: -0.02,
        color: '#1a1a1a',
        binding: {
          source: 'entry.date',
          entryId: 62,
          value: '2026-08-19',
        },
        overridden: false,
      } as BookElement,
    ],
  },
  {
    id: 'ref-5',
    background: null,
    elements: [
      {
        id: 'p-adrg53f',
        frame: {
          x: 0.025,
          y: 0.025,
          w: 0.475,
          h: 0.9512,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        kind: 'photo',
        photoId: null,
        fit: 'cover',
        focalX: 0.5,
        focalY: 0.5,
        radius: 0,
        filter: 'none',
        mask: null,
        frameStyle: 'none',
      } as BookElement,
      {
        id: 't-crm4sem',
        frame: {
          x: 0.5297,
          y: 0.119,
          w: 0.4258,
          h: 0.8012,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        kind: 'text',
        text: 'Lorem ipsum dolor sit amet',
        font: 'sans',
        size: 0.2381,
        weight: 700,
        italic: false,
        align: 'left',
        leading: 1.1,
        tracking: -0.02,
        color: '#1a1a1a',
        binding: {
          source: 'entry.title',
          entryId: 62,
        },
        overridden: false,
      } as BookElement,
      {
        id: 's-3dhohc7',
        frame: {
          x: 1.0762,
          y: 0.3541,
          w: 0.5,
          h: 0.0024,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        kind: 'shape',
        shape: 'rect',
        fill: '#f2f2f2',
        gradient: 'none',
        stroke: '#141414',
        strokeWidth: 0.0005,
        strokeStyle: 'solid',
        radius: 0,
      } as BookElement,
      {
        id: 't-0l6zeg7',
        frame: {
          x: 1.0762,
          y: 0.119,
          w: 0.8346,
          h: 0.2047,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        kind: 'text',
        text: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.',
        font: 'sans',
        size: 0.0476,
        weight: 400,
        italic: false,
        align: 'left',
        leading: 1.55,
        tracking: 0,
        color: '#1a1a1a',
        binding: {
          source: 'entry.story',
          entryId: 62,
        },
        overridden: false,
      } as BookElement,
      {
        id: 'p-igt1irs',
        frame: {
          x: 1.0762,
          y: 0.4469,
          w: 0.368,
          h: 0.2495,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        kind: 'photo',
        photoId: null,
        fit: 'cover',
        focalX: 0.5,
        focalY: 0.5,
        radius: 0,
        filter: 'none',
        mask: null,
        frameStyle: 'shadow',
      } as BookElement,
      {
        id: 'p-2akhm3w',
        frame: {
          x: 1.5105,
          y: 0.4469,
          w: 0.368,
          h: 0.2495,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        kind: 'photo',
        photoId: null,
        fit: 'cover',
        focalX: 0.5,
        focalY: 0.5,
        radius: 0,
        filter: 'none',
        mask: null,
        frameStyle: 'shadow',
      } as BookElement,
      {
        id: 'bd-g6o9fvm',
        frame: {
          x: 0.53,
          y: 0.4577,
          w: 0.2604,
          h: 0.062,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        font: 'sans',
        color: '#1a1a1a',
        accent: '#111111',
        kind: 'badge',
        variant: 'weather',
        text: 'Partly cloudy',
        sub: '',
        code: 'partly',
        style: 'chip',
      } as BookElement,
      {
        id: 'bd-ewxvw6v',
        frame: {
          x: 0.53,
          y: 0.5406,
          w: 0.2607,
          h: 0.062,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        font: 'sans',
        color: '#1a1a1a',
        accent: '#111111',
        kind: 'badge',
        variant: 'mood',
        text: 'Amazing',
        sub: '',
        code: 'amazing',
        style: 'chip',
      } as BookElement,
      {
        id: 't-az8f0nc',
        frame: {
          x: 0.5297,
          y: 0.0858,
          w: 0.36,
          h: 0.0347,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        kind: 'text',
        text: 'August 19, 2026',
        font: 'sans',
        size: 0.0714,
        weight: 700,
        italic: false,
        align: 'left',
        leading: 1.1,
        tracking: -0.02,
        color: '#1a1a1a',
        binding: {
          source: 'entry.date',
          entryId: 62,
          value: '2026-08-19',
        },
        overridden: false,
      } as BookElement,
    ],
  },
  {
    id: 'ref-6',
    background: null,
    elements: [
      {
        id: 's-7go39mg',
        frame: {
          x: 0.0238,
          y: 0.309,
          w: 0.9524,
          h: 0.666,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        kind: 'shape',
        shape: 'triangle',
        fill: '#141414',
        gradient: 'none',
        stroke: null,
        strokeWidth: 0,
        strokeStyle: 'solid',
        radius: 0,
      } as BookElement,
      {
        id: 'p-a9065nh',
        frame: {
          x: 0.0238,
          y: 0.0238,
          w: 0.2745,
          h: 0.9512,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        kind: 'photo',
        photoId: null,
        fit: 'cover',
        focalX: 0.5,
        focalY: 0.5,
        radius: 0,
        filter: 'none',
        mask: null,
        frameStyle: 'none',
      } as BookElement,
      {
        id: 'p-fvcm5kq',
        frame: {
          x: 0.3628,
          y: 0.0914,
          w: 0.2745,
          h: 0.8848,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        kind: 'photo',
        photoId: null,
        fit: 'cover',
        focalX: 0.5,
        focalY: 0.5,
        radius: 0,
        filter: 'none',
        mask: null,
        frameStyle: 'none',
      } as BookElement,
      {
        id: 'p-aski19e',
        frame: {
          x: 0.7017,
          y: 0.0238,
          w: 0.2745,
          h: 0.9512,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        kind: 'photo',
        photoId: null,
        fit: 'cover',
        focalX: 0.5,
        focalY: 0.5,
        radius: 0,
        filter: 'none',
        mask: null,
        frameStyle: 'none',
      } as BookElement,
      {
        id: 'p-tfs5cdi',
        frame: {
          x: 1.0238,
          y: 0.0238,
          w: 0.9524,
          h: 0.45,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        kind: 'photo',
        photoId: null,
        fit: 'cover',
        focalX: 0.5,
        focalY: 0.5,
        radius: 0,
        filter: 'none',
        mask: null,
        frameStyle: 'none',
      } as BookElement,
      {
        id: 't-9zjrvsn',
        frame: {
          x: 1.0592,
          y: 0.5,
          w: 0.8476,
          h: 0.0518,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        kind: 'text',
        text: 'Lorem ipsum dolor sit amet',
        font: 'sans',
        size: 0.1048,
        weight: 700,
        italic: false,
        align: 'left',
        leading: 1.1,
        tracking: -0.02,
        color: '#1a1a1a',
        binding: {
          source: 'entry.title',
          entryId: 62,
        },
        overridden: false,
      } as BookElement,
      {
        id: 't-4lgyrab',
        frame: {
          x: 1.0592,
          y: 0.5682,
          w: 0.8476,
          h: 0.1995,
        },
        rotation: 0,
        opacity: 1,
        locked: false,
        kind: 'text',
        text: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.',
        font: 'sans',
        size: 0.0476,
        weight: 400,
        italic: false,
        align: 'left',
        leading: 1.55,
        tracking: 0,
        color: '#1a1a1a',
        binding: {
          source: 'entry.story',
          entryId: 62,
        },
        overridden: false,
      } as BookElement,
    ],
  },
]
